language: ruby
rvm:
  - 1.9.3
  - jruby-19mode
  - ruby-head
  - jruby-head

script: bundle exec rake spec

notifications:
  email: true

services:
  - mongodb

branches:
  only:
    - master

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: ruby-head
    - rvm: jruby-head