language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - ruby-head

script: "export DISPLAY=:99.0 && bundle exec rspec"

services:
  - mongodb

branches:
  only:
    - master

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
