language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - ruby-head

env: TRAVIS=true

before_install:
  - gem update --system
  - gem --version

bundler_args: --without development

before_script:
  - export DISPLAY=:99.0
  - phantomjs --version

script: bundle exec rspec --tag ~statistics

services:
  - mongodb

branches:
  only:
    - master

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
