language: ruby
rvm:
  - 1.9.3
  - ruby-head

script: bundle exec rake spec

notifications:
  email: true

services:
  - mongodb

branches:
  only:
    - master

matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1680x1050x16"
