defaults: &defaults
  mongo: &mongo_defaults
    host: 127.0.0.1
    port: 27017
  stats: &stats_defaults
    host: 127.0.0.1
    port: 27017
    db: stats
    frequency: 20s
    path: "~/mongo"
    logpath: "~/mongo/logs"
    size: 52428800 # 50 MB collections

development:
  <<: *defaults

test:
  <<: *defaults
  mongo:
    <<: *mongo_defaults
    database: mongo_tools_test
  stats:
    <<: *stats_defaults
    stats_port: 27017

production:
  <<: *defaults