stats: &stats
  stats_host: 127.0.0.1
  stats_port: 27018
  stats_db_name: stats
  frequency: 20s
  path: "~/mongo"
  logpath: "~/mongo/logs"
  size: 52428800 # 50 MB collections

development:
  <<: *stats

test:
  <<: *stats

production:
  <<: *stats


